import logging
from typing import Optional

import httpx
from tenacity import retry, stop_after_attempt, wait_exponential

logger = logging.getLogger(__name__)

SENDGRID_API_URL = "https://api.sendgrid.com/v3/mail/send"


class SendGridError(Exception):
    """SendGrid API error."""
    pass


class SendGridClient:
    def __init__(self, api_key: Optional[str] = None, from_email: Optional[str] = None):
        """
        Initialize SendGrid client.
        
        Args:
            api_key: SendGrid API key (if None, reads from settings)
            from_email: Sender email address (if None, reads from settings)
        """
        if api_key is None or from_email is None:
            from gem_strategy_assistant.config import settings
            api_key = api_key or settings.sendgrid_api_key
            from_email = from_email or settings.sendgrid_from_email

        if not api_key:
            raise SendGridError("SENDGRID_API_KEY not configured")
        if not from_email:
            raise SendGridError("SENDGRID_FROM_EMAIL not configured")

        self.api_key = api_key
        self.from_email = from_email
        self.headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

    @retry(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=2, max=10),
    )
    def _make_request(self, payload: dict) -> dict:
        """Make API request to SendGrid."""
        try:
            with httpx.Client(timeout=30.0) as client:
                response = client.post(
                    SENDGRID_API_URL, 
                    json=payload, 
                    headers=self.headers
                )
                response.raise_for_status()
                
                if response.status_code == 202:
                    return {"status": "accepted", "status_code": 202}
                
                return response.json() if response.content else {}
                
        except httpx.HTTPStatusError as e:
            logger.error(f"SendGrid API error {e.response.status_code}: {e.response.text}")
            raise SendGridError(f"API returned {e.response.status_code}") from e
        except httpx.RequestError as e:
            logger.error(f"SendGrid request failed: {e}")
            raise SendGridError(f"Request failed: {e}") from e

    def send_email(
        self, 
        to_email: str, 
        subject: str, 
        content: str,
        content_type: str = "text/plain"
    ) -> dict:
        """
        Send an email via SendGrid.
        
        Args:
            to_email: Recipient email address
            subject: Email subject
            content: Email body content
            content_type: Content type ("text/plain" or "text/html")
            
        Returns:
            Response dictionary with status
            
        Raises:
            SendGridError: If sending fails
        """
        logger.info(f"Sending email to {to_email}: {subject}")
        
        payload = {
            "personalizations": [
                {
                    "to": [{"email": to_email}],
                    "subject": subject,
                }
            ],
            "from": {"email": self.from_email},
            "content": [
                {
                    "type": content_type,
                    "value": content,
                }
            ],
        }
        
        try:
            result = self._make_request(payload)
            logger.info(f"✅ Email sent successfully to {to_email}")
            return result
        except SendGridError as e:
            logger.error(f"❌ Failed to send email: {e}")
            raise

    def send_signal_notification(
        self, 
        to_email: str, 
        signal_type: str,
        etf_name: str,
        details: str
    ) -> dict:
        """
        Send a trading signal notification email.
        
        Args:
            to_email: Recipient email address
            signal_type: Type of signal ("BUY", "SELL", "HOLD")
            etf_name: Name of the ETF
            details: Additional details about the signal
            
        Returns:
            Response dictionary with status
        """
        subject = f"🚨 Momentum Signal: {signal_type} {etf_name}"
        
        content = f"""
Momentum ETF Strategy Alert
============================

Signal Type: {signal_type}
ETF: {etf_name}

Details:
{details}

---
Generated by Momentum ETF Assistant
        """.strip()
        
        return self.send_email(to_email, subject, content)
